language: python
python:
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"
  - "3.12"
  # - "nightly"
  # TODO: add nightly back when this issue is fixed: https://github.com/cython/cython/issues/3266
addons:
  apt:
    sources:
      - sourceline: 'ppa:openjdk-r/ppa'
      - sourceline: 'deb http://www.apache.org/dist/cassandra/debian 311x main'
        key_url: &apache-key https://www.apache.org/dist/cassandra/KEYS
      - sourceline: 'deb-src http://www.apache.org/dist/cassandra/debian 311x main'
        key_url: *apache-key
    packages:
      - cython3
      - openjdk-8-jdk
      - cassandra
services:
  - cassandra
  - mongodb
install:
  # Disable Cassandra optional extensions (faster testing).
  - export CASS_DRIVER_NO_EXTENSIONS=1
  - pip install -e .[test]
  - if [[ $TRAVIS_PYTHON_VERSION == '3.8' || $TRAVIS_PYTHON_VERSION == '3.9' || $TRAVIS_PYTHON_VERSION == '3.10' || $TRAVIS_PYTHON_VERSION == '3.11' || $TRAVIS_PYTHON_VERSION == '3.12' ]]; then pip install -e .[experimental_aio]; fi
before_script:
  - bash travis/wait_for_cassandra.sh
script:
  # Run non aio tests first because Python versions before 3.6 does not support aio.
  - export DO_TEST_CASSANDRA=true
  - nosetests --exclude-dir=test/aio
  # Run aio tests.
  - export DO_TEST_MONGO=true
  - if [[ $TRAVIS_PYTHON_VERSION == '3.8' || $TRAVIS_PYTHON_VERSION == '3.9' || $TRAVIS_PYTHON_VERSION == '3.10' || $TRAVIS_PYTHON_VERSION == '3.11' || $TRAVIS_PYTHON_VERSION == '3.12' ]]; then nosetests test.aio; fi
