language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly"
services:
  - mongodb
install:
  - pip install -e .[test]
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' || $TRAVIS_PYTHON_VERSION == 'nightly' ]]; then pip install -e .[experimental_aio]; fi
script:
  # Run non aio tests first because Python versions before 3.5 does not support aio.
  - nosetests --exclude-dir=test/aio
  # Run Mongo integration tests.
  - export DO_TEST_MONGO=true
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' || $TRAVIS_PYTHON_VERSION == 'nightly' ]]; then nosetests test.test_lsh_mongo; fi
