# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python Test and Publish Doc.

# Triggers the workflow on push or pull request events
on: [push, pull_request]

jobs:
  build:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        mongodb-version: ["latest"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Cassandra
        uses: fabasoad/setup-cassandra-action@v1.0.2
      - name: Setup MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      # - name: Install and Start Cassandra
      #   run: |
      #     echo "deb http://debian.datastax.com/community stable main" | sudo tee -a /etc/apt/sources.list.d/cassandra.sources.list
      #     curl -L http://debian.datastax.com/debian/repo_key | sudo apt-key add -
      #     sudo apt-get update
      #     sudo apt-get install openjdk-8-jdk
      #     java -version
      #     sudo apt-get install cassandra cython3
      #     bash travis/wait_for_cassandra.sh
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Install package
        run: |
          # Disable Cassandra optional extensions (faster testing).
          export CASS_DRIVER_NO_EXTENSIONS=1
          pip install -e .[test,experimental_aio]
      # - name: Lint with flake8
      #   run: |
      #     # stop the build if there are Python syntax errors or undefined names
      #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      #     # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
      #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          export DO_TEST_MONGO=true
          export DO_TEST_CASSANDRA=true
          pytest
      - name: Compile documentation
        if: ${{ matrix.python-version == '3.8' }}
        run: |
          python -m pip install sphinx
          cd docs
          make html
      - name: Deploy to GitHub pages
        if: ${{ github.ref == 'refs/heads/master' && matrix.python-version == '3.8' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs/_build/html
          CLEAN: true
